# Generated by Django 4.1.2 on 2022-11-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_initial', models.TextField()),
                ('trk', models.IntegerField()),
                ('equipment_number', models.IntegerField()),
                ('current_yard_circ7', models.CharField(max_length=10)),
                ('current_train_date', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbdv_name', models.CharField(max_length=30)),
                ('trk_sys_nbr', models.IntegerField()),
                ('dist', models.FloatField()),
                ('car_capacity', models.IntegerField()),
            ],
        ),
    ]
