# Generated by Django 4.1.2 on 2022-11-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_capacity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Testyard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbdv_name', models.CharField(db_column='SBDV_NAME', max_length=30)),
                ('trk_sys_nbr', models.CharField(db_column='TRK_SYS_NBR', max_length=30)),
                ('dist', models.CharField(max_length=30)),
                ('car_capacity', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'testYard',
                'managed': True,
            },
        ),
    ]
