# Generated by Django 4.1.2 on 2022-11-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_capacity', '0002_file_yardScheduler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_initial', models.TextField()),
                ('equipment_number', models.IntegerField(max_length=1000)),
                ('current_yard_circ_7', models.IntegerField(max_length=1000)),
                ('current_train_date', models.TextField()),
                ('dest_track', models.IntegerField(max_length=1000)),
            ],
        ),
    ]
